/home/uty/intelFPGA_lite/19.1/quartus/eda/sim_lib/altera_mf.v
../../soc/cpu6/defines.v 
../../soc/cpu6/cpu6_core.v 
../../soc/cpu6/cpu6_controller.v 
../../soc/cpu6/cpu6_maindec.v 
../../soc/cpu6/cpu6_aludec.v 
../../soc/cpu6/cpu6_datapath.v 
../../soc/cpu6/cpu6_dffs.v 
../../soc/cpu6/cpu6_adder.v 
../../soc/cpu6/cpu6_sl1.v 
../../soc/cpu6/cpu6_mux2.v 
../../soc/cpu6/cpu6_regfile.v 
../../soc/cpu6/cpu6_signext.v 
../../soc/cpu6/cpu6_alu.v 
../../soc/cpu6/cpu6_immdec.v 
../../soc/cpu6/cpu6_branchdec.v 
../../soc/cpu6/cpu6_pipelinereg_ifid.v 
../../soc/cpu6/cpu6_pipelinereg_idex.v 
../../soc/cpu6/cpu6_pipelinereg_exmem.v 
../../soc/cpu6/cpu6_pipelinereg_memwb.v 
../../soc/cpu6/cpu6_hazardcontrol.v 
../../soc/cpu6/cpu6_hazardunit.v 
../../soc/cpu6/cpu6_excp.v 
../../soc/cpu6/cpu6_csr.v 
../../soc/cpu6/ram.v 
../../soc/vga/vga640x480.v 
../../soc/vga/vgaram.v 
../../soc/vga/text80x25.v
../../soc/vga/hvsync.v
../../soc/vga/vgatextram.v
../../soc/vga/chrom.v
../../soc/soc_top.v
../../tb/test11_csrrci_soc_top_tb.v

